version: '3.0'

services:
  db:
    container_name: pgvector_container
    image: ankane/pgvector
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-vectordb}
      - POSTGRES_USER=${POSTGRES_USER:-testuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-testpwd}
      - POSTGRES_HOST_AUTH_METHOD=trust

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped